import React, { useState, useEffect } from "react";
import { 
  MessageSquare, Plus, CheckCircle, Clock, ChevronDown, 
  Send, AlertTriangle, HelpCircle, PhoneCall, Sparkles, 
  Layers, ShieldAlert, ArrowUpRight, Check, X, Search, ChevronRight, User, RefreshCw
} from "lucide-react";
import { UserAccount } from "../types";
import { db } from "../lib/firebase";
import { collection, addDoc, query, where, onSnapshot } from "firebase/firestore";
import { toast } from "react-hot-toast";
import { motion, AnimatePresence } from "motion/react";
import { sanitizeInput } from "../lib/security";

interface TicketsProps {
  currentUser: UserAccount | null;
}

interface QuickTopic {
  tag: string;
  label: string;
  desc: string;
}

const QUICK_TOPICS: QuickTopic[] = [
  { tag: "verification", label: "OTP Verification Delay", desc: "For purchased virtual numbers where the SMS verification code was not received." },
  { tag: "deposit", label: "Payment & Balance Processing", desc: "For manual deposit receipts, voucher errors, or credit discrepancies." },
  { tag: "api", label: "Developer API Support", desc: "For developer keys, custom endpoints, rate limits, or SMM portal syncs." },
  { tag: "other", label: "Other General Inquiry", desc: "General questions about vendor programs, custom numbers, or affiliate links." }
];

const FAQS = [
  {
    q: "Why didn't my virtual number receive the SMS code?",
    a: "Verification delays depend heavily on the target service provider's global routing. If no code arrives within 15 minutes, your line is automatically cancelled and 100% of the funds are refunded back to your balance immediately."
  },
  {
    q: "How long does it take to process manual Easypaisa/JazzCash deposits?",
    a: "Manual receipts are reviewed and credited within 10 to 30 minutes. Always ensure you provide the exact TRX ID / Transaction Hash to avoid verification bottlenecks."
  },
  {
    q: "Can I request custom dedicated SMM and Virtual numbers?",
    a: "Absolutely. Premium custom requests can be requested by raising a dedicated ticket or contacting our VIP support desk on WhatsApp."
  }
];

export default function Tickets({ currentUser }: TicketsProps) {
  const [tickets, setTickets] = useState<any[]>([]);
  const [isCreating, setIsCreating] = useState(false);
  const [subject, setSubject] = useState("");
  const [message, setMessage] = useState("");
  const [selectedTag, setSelectedTag] = useState<string>("verification");
  const [orderId, setOrderId] = useState(""); // Optional custom transaction/order ID
  const [submitting, setSubmitting] = useState(false);

  // Search & Filters
  const [searchQuery, setSearchQuery] = useState("");
  const [activeFilter, setActiveFilter] = useState<"all" | "open" | "resolved">("all");

  // Expanded ticket ID state
  const [expandedTicketId, setExpandedTicketId] = useState<string | null>(null);

  // Simulated Chat responses for specific statuses
  const [chatInputs, setChatInputs] = useState<{ [key: string]: string }>({});

  useEffect(() => {
    if (!currentUser) return;
    const q = query(
      collection(db, "tickets"),
      where("userId", "==", currentUser.id)
    );
    const unsubscribe = onSnapshot(q, (snapshot) => {
      const dbTickets: any[] = [];
      snapshot.forEach((doc) => {
        dbTickets.push({ id: doc.id, ...doc.data() });
      });
      dbTickets.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
      setTickets(dbTickets);
    });
    return () => unsubscribe();
  }, [currentUser]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!currentUser) return;
    
    setSubmitting(true);
    const defaultSubject = subject.trim() || QUICK_TOPICS.find(t => t.tag === selectedTag)?.label || "General Support Ticket";

    try {
      await addDoc(collection(db, "tickets"), {
        userId: currentUser.id,
        userEmail: currentUser.email,
        username: currentUser.username,
        subject: sanitizeInput(defaultSubject),
        message: sanitizeInput(message.trim()),
        category: selectedTag,
        orderId: sanitizeInput(orderId.trim()),
        status: "open",
        createdAt: new Date().toISOString()
      });
      
      // Trigger Ticket Opened Email Confirmation
      fetch("/api/email/ticket-opened", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          toEmail: currentUser.email,
          username: currentUser.username,
          ticketId: "NEW", // The ID will be generated by Firestore, but for confirmation we can use a placeholder or wait for the ref
          subject: defaultSubject
        })
      }).catch(err => console.error("Ticket confirmation email failed", err));

      // Trigger Admin Alert for New Ticket
      fetch("/api/email/admin-new-ticket", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          username: currentUser.username,
          ticketId: "NEW",
          subject: defaultSubject,
          category: selectedTag
        })
      }).catch(err => console.error("Admin ticket alert failed", err));

      // Send Admin Alert
      fetch("/api/admin/alert/trigger", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          type: "new_ticket",
          details: `Username: ${currentUser.username || "Unknown"}\nUser ID: ${currentUser.id}\nUser Email: ${currentUser.email || "N/A"}\n\n--- Ticket Details ---\nCategory: ${selectedTag}\nSubject: ${defaultSubject}\nLinked Order ID: ${orderId.trim() || "None"}\n\nMessage:\n${message.trim()}`
        })
      }).catch(err => console.error("Alert trigger failed", err));

      toast.success("Support ticket logged successfully!");
      setIsCreating(false);
      setSubject("");
      setMessage("");
      setOrderId("");
    } catch (err: any) {
      toast.error("Failed to register support ticket. Please try again.");
    } finally {
      setSubmitting(false);
    }
  };

  const handleSendReply = (ticketId: string) => {
    const text = chatInputs[ticketId]?.trim();
    if (!text) return;

    // Simulate sending a follow-up reply in UI (just adding local feedback)
    toast.success("Inquiry response recorded successfully!");
    setChatInputs(prev => ({ ...prev, [ticketId]: "" }));
  };

  // Filter logic
  const filteredTickets = tickets.filter(t => {
    const matchesSearch = t.subject?.toLowerCase().includes(searchQuery.toLowerCase()) || 
                          t.message?.toLowerCase().includes(searchQuery.toLowerCase()) ||
                          t.orderId?.toLowerCase().includes(searchQuery.toLowerCase());
    
    if (activeFilter === "all") return matchesSearch;
    return t.status === activeFilter && matchesSearch;
  });

  if (!currentUser) {
    return (
      <div className="bg-white rounded-2xl p-8 border border-slate-200 text-center max-w-lg mx-auto space-y-5 animate-in fade-in duration-300">
        <div className="w-16 h-16 bg-slate-50 border border-slate-100 rounded-2xl flex items-center justify-center mx-auto text-slate-400">
          <MessageSquare className="h-7 w-7" />
        </div>
        <div className="space-y-1.5">
          <h3 className="text-base font-bold text-slate-900">Support Desk Login Required</h3>
          <p className="text-xs text-slate-500 max-w-xs mx-auto leading-relaxed">
            Please log in to your account credentials to view, submit, or track active support queries.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-8 text-slate-800 animate-in fade-in duration-500 pb-12">
      
      {/* Premium Gradient Header */}
      <div className="bg-gradient-to-br from-slate-900 via-slate-950 to-indigo-950 rounded-2xl p-6 sm:p-10 text-white shadow-xl relative overflow-hidden border border-slate-800">
        <div className="absolute -right-20 -top-20 opacity-[0.03] pointer-events-none transform select-none">
          <MessageSquare className="w-[500px] h-[500px]" />
        </div>

        <div className="relative z-10 flex flex-col lg:flex-row lg:items-center justify-between gap-6">
          <div className="space-y-1">
            <span className="inline-flex items-center gap-1.5 bg-indigo-500/10 border border-indigo-500/25 px-3 py-1 rounded-full text-[10px] font-semibold tracking-wider uppercase text-indigo-300">
              <Sparkles className="w-3 h-3 text-amber-400 animate-pulse" />
              VIP Support & Dispute Center
            </span>
            <h2 className="text-2xl sm:text-4xl font-extrabold tracking-tight mt-2 text-slate-100">
              Support Desk
            </h2>
            <p className="max-w-2xl text-slate-300 text-xs sm:text-sm leading-relaxed font-light mt-1">
              Connect with our live resolution team or self-serve with smart diagnostics. We trace, analyze, and troubleshoot SMM fulfillments, manual cash deposits, and temporary virtual lines 24 hours a day.
            </p>
          </div>

          {/* Quick contact direct fallback cards */}
          <div className="flex flex-col sm:flex-row gap-3 self-start lg:self-center shrink-0 w-full sm:w-auto">
            <a
              href="https://wa.me/447868713315?text=Hello%20ZeroX%20Support!%20I%20need%20help%20with%20my%20account."
              target="_blank"
              rel="noreferrer"
              className="bg-emerald-600 hover:bg-emerald-700 text-white font-bold px-4 py-3 rounded-xl text-xs transition flex items-center justify-center gap-2 shadow-sm active:scale-95"
            >
              <PhoneCall className="w-4 h-4 text-emerald-300" />
              <span>Direct WhatsApp Desk</span>
              <ArrowUpRight className="w-3.5 h-3.5 opacity-60" />
            </a>

            <button
              type="button"
              onClick={() => setIsCreating(!isCreating)}
              className="bg-indigo-600 hover:bg-indigo-700 text-white font-bold px-4 py-3 rounded-xl text-xs transition flex items-center justify-center gap-2 shadow-sm active:scale-95 cursor-pointer outline-none"
            >
              <Plus className="w-4 h-4 text-indigo-300" />
              <span>{isCreating ? "Discard Ticket" : "Initiate Support Ticket"}</span>
            </button>
          </div>
        </div>
      </div>

      {/* Interactive Form for Ticket Creation */}
      <AnimatePresence mode="wait">
        {isCreating && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: "auto" }}
            exit={{ opacity: 0, height: 0 }}
            transition={{ duration: 0.3 }}
            className="overflow-hidden"
          >
            <form onSubmit={handleSubmit} className="bg-white border border-slate-200/80 rounded-2xl p-6 shadow-sm space-y-6">
              <div className="flex items-center justify-between border-b border-slate-100 pb-4">
                <div className="flex items-center gap-2">
                  <Plus className="w-4.5 h-4.5 text-indigo-600" />
                  <h3 className="text-sm font-bold text-slate-900">1. Draft New Platform Ticket</h3>
                </div>
                <button
                  type="button"
                  onClick={() => setIsCreating(false)}
                  className="text-slate-400 hover:text-slate-600 transition"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>

              {/* Tag / Category Picker */}
              <div className="space-y-2">
                <label className="block text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                  Select Ticket Issue Category
                </label>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
                  {QUICK_TOPICS.map((topic) => (
                    <button
                      key={topic.tag}
                      type="button"
                      onClick={() => setSelectedTag(topic.tag)}
                      className={`text-left p-4 rounded-xl border transition-all ${
                        selectedTag === topic.tag
                          ? "bg-indigo-50/50 border-indigo-400 shadow-sm"
                          : "bg-slate-50 border-slate-200 hover:bg-slate-100/50"
                      }`}
                    >
                      <div className="flex items-center justify-between mb-1.5">
                        <span className={`text-[10px] font-extrabold uppercase px-2 py-0.5 rounded ${
                          selectedTag === topic.tag ? "bg-indigo-600 text-white" : "bg-slate-200 text-slate-700"
                        }`}>
                          {topic.tag}
                        </span>
                        {selectedTag === topic.tag && <Check className="w-4 h-4 text-indigo-600" />}
                      </div>
                      <h4 className="text-xs font-bold text-slate-800 tracking-tight">{topic.label}</h4>
                      <p className="text-[10px] text-slate-400 font-light leading-normal mt-1">{topic.desc}</p>
                    </button>
                  ))}
                </div>
              </div>

              {/* Subject & Optional transaction inputs */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="space-y-1.5">
                  <label className="block text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                    Inquiry Headline (Subject)
                  </label>
                  <input
                    type="text"
                    required
                    value={subject}
                    onChange={(e) => setSubject(e.target.value)}
                    placeholder="e.g. Code did not deliver for WhatsApp verification"
                    className="w-full bg-slate-50 border border-slate-200 rounded-lg px-3.5 py-2.5 text-xs font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-indigo-500/10 focus:bg-white transition-all"
                  />
                </div>

                <div className="space-y-1.5">
                  <label className="block text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                    Transaction ID / SMM Order ID <span className="text-slate-400 font-normal">(Optional)</span>
                  </label>
                  <input
                    type="text"
                    value={orderId}
                    onChange={(e) => setOrderId(e.target.value)}
                    placeholder="e.g. ord_5521948 or deposit_trx_hash"
                    className="w-full bg-slate-50 border border-slate-200 rounded-lg px-3.5 py-2.5 text-xs font-mono text-slate-800 focus:outline-none focus:ring-2 focus:ring-indigo-500/10 focus:bg-white transition-all"
                  />
                </div>
              </div>

              {/* Message Description */}
              <div className="space-y-1.5">
                <label className="block text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                  Detailed Explanation
                </label>
                <textarea
                  required
                  rows={4}
                  value={message}
                  onChange={(e) => setMessage(e.target.value)}
                  placeholder="Describe your issue with all helpful details (e.g., operator selected, voucher image details, exact time of transfer) to ensure rapid resolution..."
                  className="w-full bg-slate-50 border border-slate-200 rounded-lg px-3.5 py-2.5 text-xs font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-indigo-500/10 focus:bg-white transition-all resize-none leading-relaxed"
                />
              </div>

              {/* Action buttons */}
              <div className="flex justify-end gap-3 pt-2">
                <button
                  type="button"
                  onClick={() => setIsCreating(false)}
                  className="bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold px-4 py-2 rounded-lg text-xs transition"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={submitting}
                  className="bg-indigo-600 hover:bg-indigo-700 text-white font-bold px-5 py-2 rounded-lg text-xs transition flex items-center gap-1.5 shadow-sm active:scale-95 disabled:opacity-60"
                >
                  {submitting && <RefreshCw className="w-3.5 h-3.5 animate-spin" />}
                  <span>{submitting ? "Logging Inquiry..." : "File Official Ticket"}</span>
                </button>
              </div>
            </form>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Main Tickets List Workspace */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        
        {/* Left Hand: Tickets listing filter index (7 cols) */}
        <div className="lg:col-span-7 space-y-6">
          <div className="bg-white border border-slate-200/80 rounded-2xl p-6 shadow-sm space-y-6">
            
            {/* Toolbar search & status filters */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-100 pb-4">
              <div className="space-y-1">
                <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2">
                  <Layers className="w-4.5 h-4.5 text-indigo-600" />
                  Inquiry Log history
                </h3>
              </div>

              <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-2">
                <div className="relative">
                  <Search className="w-3.5 h-3.5 text-slate-400 absolute left-3 top-2.5" />
                  <input
                    type="text"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    placeholder="Search logs..."
                    className="bg-slate-50 border border-slate-200 rounded-lg pl-8 pr-3 py-1.5 text-xs font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-indigo-500/10"
                  />
                </div>

                <div className="flex items-center gap-0.5 bg-slate-100 p-0.5 rounded-lg text-[10px] font-bold">
                  {(["all", "open", "resolved"] as const).map(status => (
                    <button
                      key={status}
                      type="button"
                      onClick={() => setActiveFilter(status)}
                      className={`px-2 py-1 rounded transition uppercase tracking-wider ${
                        activeFilter === status ? "bg-white text-indigo-700 shadow-sm" : "text-slate-500 hover:text-slate-800"
                      }`}
                    >
                      {status}
                    </button>
                  ))}
                </div>
              </div>
            </div>

            {/* List entries */}
            <div className="space-y-3.5">
              {filteredTickets.length === 0 ? (
                <div className="text-center py-10 space-y-3 bg-slate-50 rounded-xl border border-dashed border-slate-200">
                  <HelpCircle className="h-8 w-8 text-slate-300 mx-auto" />
                  <div className="space-y-1">
                    <p className="text-xs font-bold text-slate-700">No matched inquiries found</p>
                    <p className="text-[11px] text-slate-400 font-light">Draft a support ticket above if you face any SMM, API, or number issues.</p>
                  </div>
                </div>
              ) : (
                <div className="space-y-3">
                  {filteredTickets.map(ticket => {
                    const isExpanded = expandedTicketId === ticket.id;
                    const isOpen = ticket.status === "open";

                    return (
                      <div 
                        key={ticket.id}
                        className={`bg-white border rounded-xl transition-all overflow-hidden ${
                          isExpanded 
                            ? "border-indigo-400 shadow-sm" 
                            : "border-slate-200 hover:border-slate-300"
                        }`}
                      >
                        {/* Summary Header panel */}
                        <div 
                          onClick={() => setExpandedTicketId(isExpanded ? null : ticket.id)}
                          className="p-4 flex items-start justify-between gap-4 cursor-pointer select-none"
                        >
                          <div className="space-y-1.5 min-w-0 pr-2">
                            <div className="flex items-center gap-2 flex-wrap">
                              <span className={`text-[9px] font-mono font-extrabold uppercase px-1.5 py-0.5 rounded ${
                                ticket.category === "verification" ? "bg-red-50 text-red-700 border border-red-200/40" :
                                ticket.category === "deposit" ? "bg-emerald-50 text-emerald-700 border border-emerald-200/40" :
                                "bg-slate-100 text-slate-600"
                              }`}>
                                {ticket.category || "General"}
                              </span>
                              {ticket.orderId && (
                                <span className="text-[9px] font-mono text-slate-400">
                                  ID: {ticket.orderId}
                                </span>
                              )}
                            </div>
                            <h4 className="text-xs font-bold text-slate-900 leading-snug tracking-tight">
                              {ticket.subject}
                            </h4>
                          </div>

                          <div className="flex items-center gap-3 shrink-0">
                            <div className="text-right flex flex-col items-end gap-1">
                              <span className={`text-[9px] font-bold px-2 py-0.5 rounded-full uppercase flex items-center gap-1 ${
                                isOpen ? 'bg-amber-100 text-amber-800' : 'bg-emerald-100 text-emerald-800'
                              }`}>
                                {isOpen ? <Clock className="h-2.5 w-2.5 animate-pulse" /> : <CheckCircle className="h-2.5 w-2.5" />}
                                {isOpen ? "Awaiting Agent" : "Resolved"}
                              </span>
                              <span className="text-[9px] text-slate-400 font-mono">
                                {new Date(ticket.createdAt).toLocaleDateString("en-US", { month: "short", day: "numeric" })}
                              </span>
                            </div>
                            <ChevronDown className={`w-4 h-4 text-[#00AEEF] neon-arrow-bounce transition-transform ${isExpanded ? "rotate-180" : ""}`} />
                          </div>
                        </div>

                        {/* Interactive Expandable details view */}
                        <AnimatePresence>
                          {isExpanded && (
                            <motion.div
                              initial={{ height: 0 }}
                              animate={{ height: "auto" }}
                              exit={{ height: 0 }}
                              className="overflow-hidden bg-slate-50 border-t border-slate-100"
                            >
                              <div className="p-4 space-y-4 text-xs">
                                
                                {/* Base description message */}
                                <div className="space-y-1">
                                  <span className="text-[9px] font-bold text-slate-400 uppercase tracking-widest block">Original Ticket Message:</span>
                                  <p className="text-slate-700 bg-white border border-slate-200/60 p-3.5 rounded-xl font-light leading-relaxed whitespace-pre-wrap">
                                    {ticket.message}
                                  </p>
                                </div>

                                {/* Roadmap simulation / Resolution roadmap timeline */}
                                <div className="border-l border-slate-200 pl-4 ml-2 space-y-3.5">
                                  {/* Step 1: Ticket Filed */}
                                  <div className="relative">
                                    <span className="absolute -left-6 top-0 w-4 h-4 rounded-full bg-indigo-100 border-2 border-indigo-500 flex items-center justify-center">
                                      <span className="w-1.5 h-1.5 rounded-full bg-indigo-600" />
                                    </span>
                                    <div className="space-y-0.5">
                                      <span className="font-bold text-slate-800 block text-[11px]">Ticket Registered on Cloud Ledger</span>
                                      <span className="text-[10px] text-slate-400 font-mono block">
                                        {new Date(ticket.createdAt).toLocaleString()}
                                      </span>
                                    </div>
                                  </div>

                                  {/* Step 2: Agent Response (simulated depending on status) */}
                                  {isOpen ? (
                                    <div className="relative">
                                      <span className="absolute -left-6 top-0 w-4 h-4 rounded-full bg-amber-50 border-2 border-amber-400 flex items-center justify-center">
                                        <Clock className="w-2 h-2 text-amber-500 animate-pulse" />
                                      </span>
                                      <div className="space-y-1 bg-amber-500/5 border border-amber-200/40 p-3 rounded-lg">
                                        <span className="font-bold text-amber-800 block text-[11px]">Awaiting Agent Assignment</span>
                                        <p className="text-[10px] text-slate-500 leading-normal font-light">
                                          Your ticket is queued for immediate diagnosis. Most temporary lines or activation checks are completed in less than 30 minutes. You will receive an instant push notification on resolution.
                                        </p>
                                      </div>
                                    </div>
                                  ) : (
                                    <div className="relative">
                                      <span className="absolute -left-6 top-0 w-4 h-4 rounded-full bg-emerald-50 border-2 border-emerald-500 flex items-center justify-center">
                                        <Check className="w-2 h-2 text-emerald-600" />
                                      </span>
                                      <div className="space-y-1 bg-emerald-500/5 border border-emerald-200/40 p-3 rounded-lg">
                                        <span className="font-bold text-emerald-800 block text-[11px] flex items-center gap-1.5">
                                          <Sparkles className="w-3 h-3 text-emerald-600" /> Resolution Logged by Agent "Injazify_Admin"
                                        </span>
                                        <p className="text-[10px] text-slate-600 leading-normal font-light">
                                          We have successfully inspected the order credentials. The OTP code block has been analyzed and processed or refunded back to your ledger balance. Thank you for your patience!
                                        </p>
                                        <span className="text-[9px] text-slate-400 font-mono block pt-1">
                                          Response Time: 12 minutes after creation
                                        </span>
                                      </div>
                                    </div>
                                  )}
                                </div>

                                {/* Follow Up Interactive Message Input */}
                                <div className="space-y-2 pt-2 border-t border-slate-200/60">
                                  <label className="text-[9px] font-bold text-slate-400 uppercase tracking-widest block">Add follow-up message:</label>
                                  <div className="flex gap-2">
                                    <input
                                      type="text"
                                      value={chatInputs[ticket.id] || ""}
                                      onChange={(e) => setChatInputs(prev => ({ ...prev, [ticket.id]: e.target.value }))}
                                      placeholder="Reply to this ticket inquiry thread..."
                                      className="flex-grow bg-white border border-slate-200 rounded-lg px-3 py-1.5 text-xs text-slate-800 focus:outline-none focus:ring-1 focus:ring-indigo-500"
                                    />
                                    <button
                                      type="button"
                                      onClick={() => handleSendReply(ticket.id)}
                                      className="bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg px-3.5 py-1.5 text-xs font-bold flex items-center justify-center gap-1 shrink-0 cursor-pointer"
                                    >
                                      <Send className="w-3 h-3" />
                                      <span>Send</span>
                                    </button>
                                  </div>
                                </div>

                              </div>
                            </motion.div>
                          )}
                        </AnimatePresence>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>

          </div>
        </div>

        {/* Right Hand: FAQ diagnostic accordion index (5 cols) */}
        <div className="lg:col-span-5 space-y-6">
          <div className="bg-white border border-slate-200/80 rounded-2xl p-6 shadow-sm space-y-5">
            <div className="flex items-center gap-2 border-b border-slate-100 pb-3">
              <HelpCircle className="w-4.5 h-4.5 text-indigo-600" />
              <h3 className="text-sm font-bold text-slate-900">Self-Service Diagnostics</h3>
            </div>

            <div className="space-y-3.5">
              {FAQS.map((faq, idx) => (
                <div key={idx} className="bg-slate-50 border border-slate-100 rounded-xl p-4 space-y-2">
                  <h4 className="text-xs font-bold text-slate-800 leading-snug flex items-start gap-1.5">
                    <span className="w-1.5 h-1.5 rounded-full bg-indigo-500 shrink-0 mt-1.5" />
                    {faq.q}
                  </h4>
                  <p className="text-[11px] text-slate-500 font-light leading-relaxed pl-3 border-l border-slate-200">
                    {faq.a}
                  </p>
                </div>
              ))}
            </div>

            {/* Direct escalation hotline banner */}
            <div className="bg-gradient-to-r from-indigo-50 to-indigo-100/50 border border-indigo-100 rounded-xl p-4.5 space-y-3.5">
              <div className="flex items-center gap-2">
                <ShieldAlert className="w-4.5 h-4.5 text-indigo-700" />
                <span className="text-xs font-black text-slate-900 uppercase tracking-tight">Escalate to VIP Line</span>
              </div>
              <p className="text-[11px] text-slate-600 font-light leading-relaxed">
                If your platform ticket remains unresolved, or if you require instant service setups, connect to our Direct Telecommunication desk on Telegram or WhatsApp.
              </p>
              <div className="grid grid-cols-2 gap-2 text-center text-[10px] font-bold">
                <a
                  href="https://wa.me/447868713315"
                  target="_blank"
                  rel="noreferrer"
                  className="bg-emerald-600 hover:bg-emerald-700 text-white rounded-lg py-2 cursor-pointer block border border-emerald-500/15"
                >
                  WhatsApp VIP
                </a>
                <a
                  href="https://www.instagram.com/zeroxnetworks?igsh=MTNxbTRuM25ndmJjag=="
                  target="_blank"
                  rel="noreferrer"
                  className="bg-pink-600 hover:bg-pink-700 text-white rounded-lg py-2 cursor-pointer block border border-pink-500/15"
                >
                  Instagram VIP
                </a>
              </div>
            </div>

          </div>
        </div>

      </div>

    </div>
  );
}
